### ISSUE TITLE
Support for running quorum without the transaction manager

### ISSUE THREAD

**Issue by melihbirim** [ConsenSys/qubernetes#119]
Current setup always includes at least one transactions manager. Some installation scenarios do not need a transaction manager at all and support for running GoQuourm without the transaction manager is needed.

I added a running sample 4 nodes RAFT configuration.

https://github.com/tubuarge/qubernetes/commit/3a0d3b27e936e8fe760ad398749247c627aa9618

**Comment by libby** [comment]
### Update rb scripts to support quorum only if the transaction manager is not set.
* [qube-init](https://github.com/ConsenSys/qubernetes/blob/master/qube-init) calls out the below scripts, should support
`./qube-init qubernetes-no-tm.yaml`
* [qubernetes](https://github.com/ConsenSys/qubernetes/blob/master/qubernetes)
* [quorum-config](https://github.com/ConsenSys/qubernetes/blob/master/quorum-config)
* the scripts should be able to process an empty `tm:` field, test with a file `qubernetes-no-tm.yaml` which removes the tm manager field https://github.com/ConsenSys/qubernetes/blob/master/qubernetes.yaml#L36 

with tm support:
```
  - Node_UserIdent: quorum-node1
    Key_Dir: key1
    quorum:
      quorum:
        # supported: (raft | istanbul)
        consensus: istanbul
        Quorum_Version: 2.6.0
      tm:
        # (tessera|constellation)
        Name: tessera
        Tm_Version: 0.10.4
```
without tm support:
```
  - Node_UserIdent: quorum-node1
    Key_Dir: key1
    quorum:
      quorum:
        # supported: (raft | istanbul)
        consensus: istanbul
        Quorum_Version: 2.6.0
```

### Update [k8s templates](https://github.com/ConsenSys/qubernetes/tree/master/templates/k8s) to leave out transaction manager resources if set to none.
* most importantly update [deployment template ](https://github.com/ConsenSys/qubernetes/blob/master/templates/k8s/quorum-deployment.yaml.erb) to leave out the transaction manager if it is not set.
e.g. https://github.com/ConsenSys/qubernetes/blob/master/templates/k8s/quorum-deployment.yaml.erb#L81

### Update [quorum templates](https://github.com/ConsenSys/qubernetes/tree/master/templates/quorum) to leave out generate Transaction Manger specific resources if not set.
### Updating `qctl`
Modify qctl to include option for no tm manger, e.g.  `qctl init --tm=none`
